### ISSUE TITLE
Figure our why this pbtxt is not working

### ISSUE THREAD

**Issue by hooman67** [auperatech/VMSS2.0_Documentation#13]
Pavel reported that this pbtxt is not working:
https://github.com/auperatech/VMSS2.0_Documentation/blob/cd42c590d913fee1a7d6ab34c0591ff1fecc2d14/manifest.json#L83-L89

- [x] Chengyou to investigate

**Comment by LCY02** [comment]
The issue is fixed in [#14](https://github.com/auperatech/VMSS2.0_Documentation/pull/14)
