### ISSUE TITLE
Demo doesn't run for some classifier networks

### ISSUE THREAD

**Issue by hooman67** [auperatech/VMSS2.0_Documentation#18]
instead of tiny_yolov3_vmss we should use: yolov3_voc the model name on zoo is (dk_yolov3_voc_416_416_65.42G_2.0)
we tried to do this here but it didn't work:

- [x] Find the commit in release branch that breaks demo pipeline for box classifiers

- [x] Find out why this script doesn't work https://auperatechvancouver-my.sharepoint.com/:u:/g/personal/mahdi_ghodsi_auperatech_com/EVszrH3M0JtMsgfhpxzgX0sBxPZPHThzVjpTnL_LVySadw

**Comment by LCY02** [comment]
- The demo pipeline for box classifiers and the script work in the release branch with the latest commit [2fe397](https://github.com/auperatech/ai_framework/commit/2fe397e6c8f0d545525bbf5996c56bb9cc44e19a). Although the the detection bounding boxes do not get visualized [#191](https://github.com/auperatech/ai_framework/issues/191).
- The yolov3_voc is set as the detection model in the box detector and classifier cascade pipelines [#20](https://github.com/auperatech/VMSS2.0_Documentation/pull/20)
